# Generated by Django 4.2.3 on 2023-09-14 08:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تگ عنوان اصلی')),
                ('title_tag', models.CharField(max_length=100, verbose_name='تگ-seo')),
                ('meta_desc', models.CharField(max_length=100, verbose_name='متا-تگ')),
                ('title_slug', models.CharField(blank=True, max_length=100, verbose_name='تگ-slug')),
                ('gif', models.FileField(blank=True, upload_to='course_video/')),
                ('desc_one', models.TextField(blank=True)),
                ('desc_two', models.TextField(blank=True)),
                ('banner_image', models.ImageField(default='course/default.jpg', upload_to='course_image/')),
                ('image', models.ImageField(blank=True, upload_to='course_image/')),
                ('course_type', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='PAID', max_length=4)),
                ('course_length', models.CharField(max_length=20)),
                ('course_slug', models.SlugField(default='-')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.FileField(blank=True, upload_to='course_video/')),
                ('video', models.FileField(upload_to='course_video/')),
                ('lecture_slug', models.SlugField(default='-')),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.section')),
            ],
        ),
    ]
